In [1]:
import sklearn

In [2]:
sklearn.__version__

'1.0.2'

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [23]:
import pandas as pd

In [6]:
iris = load_iris()

In [9]:
type(iris)

sklearn.utils.Bunch

In [10]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [16]:
iris.data.shape

(150, 4)

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [26]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [29]:
iris_df['label'] = iris.target

In [30]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [33]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [94]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, 
                                                    test_size=0.2) #random_state=11) 
#분리 / data가 입력값, target이 출력값, test_size :20퍼센트 / train size는 자동으로 80퍼  // 8:2로 나누었움

In [95]:
dt_clf = DecisionTreeClassifier() #객체생성 #random_state=11

In [96]:
dt_clf.fit(X_train, y_train) #지도학습

DecisionTreeClassifier()

In [97]:
y_pred = dt_clf.predict(X_test) #예측 
y_pred

array([0, 2, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 1, 2, 1])

In [98]:
y_test #예측이 맞는지 확인 (검증작업)

array([0, 2, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 1, 2, 1])

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
accuracy_score(y_test, y_pred) #신뢰도 검사

0.9333333333333333

In [55]:
dt_clf.predict([[5.4, 3, 1.7, 1.2]]) 
#한 건이 아니라 여러 건이라서 [] 두번넣기 > 학습된 형태와 같은 데이터 형태가 들어가야함

array([1])

In [56]:
iris.target_names[1]

'versicolor'

In [57]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(iris.data, iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target,pred) ########

1.0

In [ ]:
# 과소적합 : 데이터가 적음
# 과대적합 : 데이터 세밀하게 학습 다되있는 경우 >> 성능이 오히려 떨어짐 ,,  >> 교차검증 해야함 !