In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
item = ['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']

In [3]:
encoder = LabelEncoder()
encoder.fit(item) #사전을 만드는 느낌..
label = encoder.transform(item)

In [4]:
label

array([0, 1, 4, 5, 3, 2, 2])

In [5]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [6]:
encoder.inverse_transform(label) #데이터를 숫자로 바꾸는것 (인버스 붙으면 반대로)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서'], dtype='<U5')

In [69]:
#숫자 큰 값이 더 중요하다고 인식 > 값의 크기를 조절해야 함 >> 원핫인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [8]:
item = [['TV'],['냉장고'],['전자레인지'],['컴퓨터'],['선풍기'],['선풍기'],['믹서'],['믹서']] #한 행에 한 건의 데이터.. > 힘들기 때문에 reshape 씀!
item = np.array(item).reshape(-1,1) #배열로 바꾼다음 reshape

In [9]:
oh_encoder = OneHotEncoder() # 2차원 형태([[]])로 뽑아야한다 ~.. 
oh_encoder.fit(item)
oh_label = oh_encoder.transform(item)
oh_label.toarray() #데이터 뽑아서 보려면toarray써서 배열로 뽑아와야함

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [10]:
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [11]:
pd.get_dummies(df) #원핫인코딩은 이거 쓰거나 아까 사이킷런 쓰면됨 > 숫자의 크기가 모델에 영향 > 원핫인코딩 // 영향을 안준다 > 레이블 인코딩
#원핫인코딩 >> 컬럼 수가 많으면 별로임

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [31]:
from sklearn.datasets import load_iris

In [51]:
iris = load_iris()

In [52]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [53]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [54]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)

In [57]:
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

In [58]:
iris_scaled.mean()

-1.4684549872375404e-15

In [59]:
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [60]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [61]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [62]:
from sklearn.preprocessing import MinMaxScaler

In [65]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)

In [66]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

In [76]:
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
iris_df_scaled.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [67]:
iris_df_scaled.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [71]:
train_array = np.arange(0,11).reshape(-1,1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [72]:
test_array = np.arange(0,6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [73]:
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_array)

In [74]:
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [75]:
scaler.transform(test_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])